markdown: kramdown
permalink: /:title/
url: http://urururbain.github.io
name: Urbain
author: Urbain
qq: 313662349
email: urururbain@163.com
duoshuo: urururbain
weibo: apphe7@163.com
github: urururbain
highlighter: pygments
safe: true
paginate: 15
about: "喜欢互联网科技。"
